I hate myself
LegacyRewoven/rewoven-api pull request #26
Opened 2022-01-05 17:05 UTC by PseudoDistant

I need to fix my IDEA setup...

2022-01-05 17:07 UTC, PseudoDistant commented
Accidentally pushed to the org instead of my branch.

2022-01-05 17:11 UTC, arthurbambou approved these changes

2022-03-30 01:58 UTC, PseudoDistant reviewed
Yes

2022-04-04 13:46 UTC, arthurbambou requested changes

2022-04-04 13:46 UTC, arthurbambou commented on README.md
> +For support, consider joining the [Legacy Fabric discord server](https://discord.gg/emgF7bp), opening an issue, or creating a discussion.
```suggestion
For support, consider joining the [Legacy Fabric discord server](https://legacyfabric.net/discord), opening an issue, or creating a discussion.
```

2022-04-04 13:46 UTC, thecatcore commented on build.gradle
> +//				implementation project(path: ":${it.name}", configuration: "dev")
```suggestion
				implementation project(path: ":${it.name}", configuration: "dev")
```

2022-04-04 13:46 UTC, thecatcore commented on modules/base/src/main/resources/fabric.mod.json
> +    "homepage": "https://legacy-fabric.github.io/",
```suggestion
    "homepage": "https://legacyfabric.net/",
```

2022-04-04 13:46 UTC, thecatcore commented on modules/client/keybindings/src/main/resources/fabric.mod.json
> +    "homepage": "https://legacy-fabric.github.io/",
```suggestion
    "homepage": "https://legacyfabric.net/",
```

2022-04-04 13:46 UTC, arthurbambou commented on modules/client/rendering/src/main/resources/fabric.mod.json
> +    "homepage": "https://legacy-fabric.github.io/",
```suggestion
    "homepage": "https://legacyfabric.net/",
```

2022-04-04 13:46 UTC, arthurbambou commented on modules/crash-report-info/src/main/resources/fabric.mod.json
> +    "homepage": "https://legacy-fabric.github.io/",
```suggestion
    "homepage": "https://legacyfabric.net/",
```

2022-04-04 13:46 UTC, thecatcore commented on modules/entity-events/src/main/resources/fabric.mod.json
> +    "homepage": "https://legacy-fabric.github.io/",
```suggestion
    "homepage": "https://legacyfabric.net/",
```

2022-04-04 13:46 UTC, thecatcore commented on modules/lifecycle-events/src/main/resources/fabric.mod.json
> +    "homepage": "https://legacy-fabric.github.io/",
```suggestion
    "homepage": "https://legacyfabric.net/",
```

2022-04-04 13:46 UTC, arthurbambou commented on modules/networking/src/main/resources/fabric.mod.json
> +    "homepage": "https://legacy-fabric.github.io/",
```suggestion
    "homepage": "https://legacyfabric.net/",
```

2022-04-04 13:46 UTC, arthurbambou commented on modules/resources/src/main/resources/fabric.mod.json
> +    "homepage": "https://legacy-fabric.github.io/",
```suggestion
    "homepage": "https://legacyfabric.net/",
```

2022-04-04 13:46 UTC, arthurbambou commented on modules/server/gamerules/src/main/resources/fabric.mod.json
> +    "homepage": "https://legacy-fabric.github.io/",
```suggestion
    "homepage": "https://legacyfabric.net/",
```

2022-04-04 13:46 UTC, arthurbambou commented on modules/server/permissions/src/main/resources/fabric.mod.json
> +    "homepage": "https://legacy-fabric.github.io/",
```suggestion
    "homepage": "https://legacyfabric.net/",
```

2022-04-04 13:46 UTC, arthurbambou commented on modules/server/sponge-commands/src/main/resources/fabric.mod.json
>      "homepage": "https://legacyrewoven.github.io/",
```suggestion
    "homepage": "https://legacyfabric.net/",
```

2022-04-04 13:46 UTC, arthurbambou commented on modules/server/vanilla-commands/src/main/resources/fabric.mod.json
>      "homepage": "https://legacyrewoven.github.io/",
```suggestion
    "homepage": "https://legacyfabric.net/",
```

2022-04-04 13:46 UTC, arthurbambou commented on modules/server/vanilla-commands/src/main/resources/fabric.mod.json
>      "issues": "https://github.com/LegacyRewoven/rewoven-api/issues",
```suggestion
    "issues": "https://github.com/Legacy-Fabric/fabric/issues",
```

2022-04-04 13:46 UTC, arthurbambou commented on modules/server/vanilla-commands/src/main/resources/fabric.mod.json
>      "sources": "https://github.com/LegacyRewoven/rewoven-api"
```suggestion
    "sources": "https://github.com/Legacy-Fabric/fabric"
```

2022-04-04 13:46 UTC, arthurbambou commented on src/main/resources/fabric.mod.json
> +    "homepage": "https://legacy-fabric.github.io/",
```suggestion
    "homepage": "https://legacyfabric.net/",
```

2022-04-04 13:46 UTC, arthurbambou commented on modules/server/vanilla-commands/src/main/resources/fabric.mod.json
> +  "icon": "assets/legacy-fabric/icon.png",
```suggestion
  "icon": "assets/legacy-fabric-api/icon.png",
```

2022-04-04 13:46 UTC, arthurbambou commented on modules/server/sponge-commands/src/main/resources/fabric.mod.json
> +  "icon": "assets/legacy-fabric/icon.png",
```suggestion
  "icon": "assets/legacy-fabric-api/icon.png",
```

2022-04-04 13:46 UTC, arthurbambou commented on modules/server/sponge-commands/src/main/resources/fabric.mod.json
>      "issues": "https://github.com/LegacyRewoven/rewoven-api/issues",
```suggestion
    "issues": "https://github.com/Legacy-Fabric/fabric/issues",
```

2022-04-04 13:50 UTC, thecatcore commented
You also have to fix style regex

2022-04-04 14:08 UTC, merged

2022-04-04 14:13 UTC, PseudoDistant commented
I still had to fix checkstyle...